/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CollectionComment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'postId' : string,
}
export interface CollectionPost {
  'id' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'caption' : string,
  'image' : ExternalBlob,
}
export interface Comment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'postId' : string,
}
export interface CreateCollectionCommentInput {
  'content' : string,
  'postId' : string,
}
export interface CreateCollectionInput {
  'caption' : string,
  'image' : ExternalBlob,
}
export interface CreateCommentInput { 'content' : string, 'postId' : string }
export interface CreateDiscussionCommentInput {
  'content' : string,
  'postId' : string,
}
export interface CreateDiscussionInput {
  'topic' : string,
  'content' : string,
  'image' : [] | [ExternalBlob],
}
export interface CreateEventCommentInput {
  'content' : string,
  'postId' : string,
}
export interface CreateEventInput {
  'title' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export interface CreateGroupCommentInput {
  'content' : string,
  'postId' : string,
}
export interface CreateGroupPostInput {
  'content' : string,
  'groupId' : string,
  'image' : [] | [ExternalBlob],
}
export interface CreatePostInput { 'caption' : string, 'image' : ExternalBlob }
export interface CreateResourceInput { 'title' : string, 'content' : string }
export interface DiscussionComment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'postId' : string,
}
export interface DiscussionPost {
  'id' : string,
  'topic' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'image' : [] | [ExternalBlob],
}
export type EmojiId = string;
export interface EmojiReactions { 'count' : bigint, 'emoji' : string }
export interface EventComment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'postId' : string,
}
export interface EventPost {
  'id' : string,
  'title' : string,
  'createdBy' : Principal,
  'description' : string,
  'timestamp' : Timestamp,
  'image' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface GroupComment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'postId' : string,
}
export interface GroupPost {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'groupId' : string,
  'timestamp' : Timestamp,
  'image' : [] | [ExternalBlob],
}
export interface Notification {
  'id' : string,
  'notificationType' : NotificationType,
  'recipient' : Principal,
  'referenceId' : string,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Timestamp,
}
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'follow' : null };
export interface PlushiePost {
  'id' : string,
  'author' : Principal,
  'timestamp' : Timestamp,
  'caption' : string,
  'image' : ExternalBlob,
}
export type PostReactions = Array<EmojiReactions>;
export interface Resource {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
}
export type Timestamp = bigint;
export interface UserProfile { 'bio' : string, 'username' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCollectionComment' : ActorMethod<
    [CreateCollectionCommentInput],
    string
  >,
  'createCollectionPost' : ActorMethod<[CreateCollectionInput], string>,
  'createComment' : ActorMethod<[CreateCommentInput], string>,
  'createDiscussionComment' : ActorMethod<
    [CreateDiscussionCommentInput],
    string
  >,
  'createDiscussionPost' : ActorMethod<[CreateDiscussionInput], string>,
  'createEvent' : ActorMethod<[CreateEventInput], string>,
  'createEventComment' : ActorMethod<[CreateEventCommentInput], string>,
  'createGroup' : ActorMethod<[string, string], string>,
  'createGroupComment' : ActorMethod<[CreateGroupCommentInput], string>,
  'createGroupPost' : ActorMethod<[CreateGroupPostInput], string>,
  'createPost' : ActorMethod<[CreatePostInput], string>,
  'createResource' : ActorMethod<[CreateResourceInput], string>,
  'deleteGroup' : ActorMethod<[string], undefined>,
  'getAllCollectionPosts' : ActorMethod<[], Array<CollectionPost>>,
  'getAllCommunityGroups' : ActorMethod<
    [],
    Array<[string, string, string, Principal, Timestamp, Array<Principal>]>
  >,
  'getAllDiscussionPosts' : ActorMethod<[string], Array<DiscussionPost>>,
  'getAllEvents' : ActorMethod<[], Array<EventPost>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllPostReactions' : ActorMethod<[], Array<[string, PostReactions]>>,
  'getAllPosts' : ActorMethod<[], Array<PlushiePost>>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectionComments' : ActorMethod<[string], Array<CollectionComment>>,
  'getCollectionLikeCount' : ActorMethod<[string], bigint>,
  'getCommentsForPost' : ActorMethod<[string], Array<Comment>>,
  'getDiscussionComments' : ActorMethod<[string], Array<DiscussionComment>>,
  'getDiscussionLikeCount' : ActorMethod<[string], bigint>,
  'getEventComments' : ActorMethod<[string], Array<EventComment>>,
  'getGroupComments' : ActorMethod<[string], Array<GroupComment>>,
  'getGroupFeed' : ActorMethod<[string], Array<GroupPost>>,
  'getGroupMembers' : ActorMethod<[string], Array<Principal>>,
  'getLikeCount' : ActorMethod<[string], bigint>,
  'getPostsByUser' : ActorMethod<[Principal], Array<PlushiePost>>,
  'getReactions' : ActorMethod<[string], PostReactions>,
  'getResource' : ActorMethod<[string], [] | [Resource]>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserLiked' : ActorMethod<[string], boolean>,
  'hasUserLikedCollection' : ActorMethod<[string], boolean>,
  'hasUserLikedDiscussion' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserGroupMember' : ActorMethod<[string], boolean>,
  'joinGroup' : ActorMethod<[string], undefined>,
  'leaveGroup' : ActorMethod<[string], undefined>,
  'listGroupPosts' : ActorMethod<[string], Array<GroupPost>>,
  'markAllNotificationsAsRead' : ActorMethod<[], undefined>,
  'markNotificationAsRead' : ActorMethod<[string], undefined>,
  'removeUserFromGroup' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchEvents' : ActorMethod<[string], Array<EventPost>>,
  'searchGroups' : ActorMethod<
    [string],
    Array<[string, string, string, Principal, Timestamp, Array<Principal>]>
  >,
  'searchPosts' : ActorMethod<[string], Array<PlushiePost>>,
  'toggleCollectionLike' : ActorMethod<[string], undefined>,
  'toggleDiscussionLike' : ActorMethod<[string], undefined>,
  'toggleEmojiReaction' : ActorMethod<[string, EmojiId], PostReactions>,
  'toggleLike' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];