/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateCollectionCommentInput = IDL.Record({
  'content' : IDL.Text,
  'postId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateCollectionInput = IDL.Record({
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const CreateCommentInput = IDL.Record({
  'content' : IDL.Text,
  'postId' : IDL.Text,
});
export const CreateDiscussionCommentInput = IDL.Record({
  'content' : IDL.Text,
  'postId' : IDL.Text,
});
export const CreateDiscussionInput = IDL.Record({
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const CreateEventInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const CreateEventCommentInput = IDL.Record({
  'content' : IDL.Text,
  'postId' : IDL.Text,
});
export const CreateGroupCommentInput = IDL.Record({
  'content' : IDL.Text,
  'postId' : IDL.Text,
});
export const CreateGroupPostInput = IDL.Record({
  'content' : IDL.Text,
  'groupId' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const CreatePostInput = IDL.Record({
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const CreateResourceInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const CollectionPost = IDL.Record({
  'id' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const DiscussionPost = IDL.Record({
  'id' : IDL.Text,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
  'image' : IDL.Opt(ExternalBlob),
});
export const EventPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'image' : IDL.Opt(ExternalBlob),
});
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'follow' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notificationType' : NotificationType,
  'recipient' : IDL.Principal,
  'referenceId' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const EmojiReactions = IDL.Record({
  'count' : IDL.Nat,
  'emoji' : IDL.Text,
});
export const PostReactions = IDL.Vec(EmojiReactions);
export const PlushiePost = IDL.Record({
  'id' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
  'caption' : IDL.Text,
  'image' : ExternalBlob,
});
export const Resource = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
});
export const CollectionComment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
  'postId' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
  'postId' : IDL.Text,
});
export const DiscussionComment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
  'postId' : IDL.Text,
});
export const EventComment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
  'postId' : IDL.Text,
});
export const GroupComment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Timestamp,
  'postId' : IDL.Text,
});
export const GroupPost = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'groupId' : IDL.Text,
  'timestamp' : Timestamp,
  'image' : IDL.Opt(ExternalBlob),
});
export const EmojiId = IDL.Text;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCollectionComment' : IDL.Func(
      [CreateCollectionCommentInput],
      [IDL.Text],
      [],
    ),
  'createCollectionPost' : IDL.Func([CreateCollectionInput], [IDL.Text], []),
  'createComment' : IDL.Func([CreateCommentInput], [IDL.Text], []),
  'createDiscussionComment' : IDL.Func(
      [CreateDiscussionCommentInput],
      [IDL.Text],
      [],
    ),
  'createDiscussionPost' : IDL.Func([CreateDiscussionInput], [IDL.Text], []),
  'createEvent' : IDL.Func([CreateEventInput], [IDL.Text], []),
  'createEventComment' : IDL.Func([CreateEventCommentInput], [IDL.Text], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createGroupComment' : IDL.Func([CreateGroupCommentInput], [IDL.Text], []),
  'createGroupPost' : IDL.Func([CreateGroupPostInput], [IDL.Text], []),
  'createPost' : IDL.Func([CreatePostInput], [IDL.Text], []),
  'createResource' : IDL.Func([CreateResourceInput], [IDL.Text], []),
  'deleteGroup' : IDL.Func([IDL.Text], [], []),
  'getAllCollectionPosts' : IDL.Func([], [IDL.Vec(CollectionPost)], ['query']),
  'getAllCommunityGroups' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Text,
            IDL.Text,
            IDL.Principal,
            Timestamp,
            IDL.Vec(IDL.Principal),
          )
        ),
      ],
      ['query'],
    ),
  'getAllDiscussionPosts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DiscussionPost)],
      ['query'],
    ),
  'getAllEvents' : IDL.Func([], [IDL.Vec(EventPost)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllPostReactions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PostReactions))],
      ['query'],
    ),
  'getAllPosts' : IDL.Func([], [IDL.Vec(PlushiePost)], ['query']),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectionComments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CollectionComment)],
      ['query'],
    ),
  'getCollectionLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getDiscussionComments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DiscussionComment)],
      ['query'],
    ),
  'getDiscussionLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getEventComments' : IDL.Func([IDL.Text], [IDL.Vec(EventComment)], ['query']),
  'getGroupComments' : IDL.Func([IDL.Text], [IDL.Vec(GroupComment)], ['query']),
  'getGroupFeed' : IDL.Func([IDL.Text], [IDL.Vec(GroupPost)], ['query']),
  'getGroupMembers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getPostsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PlushiePost)],
      ['query'],
    ),
  'getReactions' : IDL.Func([IDL.Text], [PostReactions], ['query']),
  'getResource' : IDL.Func([IDL.Text], [IDL.Opt(Resource)], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserLiked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'hasUserLikedCollection' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'hasUserLikedDiscussion' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserGroupMember' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text], [], []),
  'leaveGroup' : IDL.Func([IDL.Text], [], []),
  'listGroupPosts' : IDL.Func([IDL.Text], [IDL.Vec(GroupPost)], ['query']),
  'markAllNotificationsAsRead' : IDL.Func([], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
  'removeUserFromGroup' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(EventPost)], ['query']),
  'searchGroups' : IDL.Func(
      [IDL.Text],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Text,
            IDL.Text,
            IDL.Principal,
            Timestamp,
            IDL.Vec(IDL.Principal),
          )
        ),
      ],
      ['query'],
    ),
  'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(PlushiePost)], ['query']),
  'toggleCollectionLike' : IDL.Func([IDL.Text], [], []),
  'toggleDiscussionLike' : IDL.Func([IDL.Text], [], []),
  'toggleEmojiReaction' : IDL.Func([IDL.Text, EmojiId], [PostReactions], []),
  'toggleLike' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateCollectionCommentInput = IDL.Record({
    'content' : IDL.Text,
    'postId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateCollectionInput = IDL.Record({
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const CreateCommentInput = IDL.Record({
    'content' : IDL.Text,
    'postId' : IDL.Text,
  });
  const CreateDiscussionCommentInput = IDL.Record({
    'content' : IDL.Text,
    'postId' : IDL.Text,
  });
  const CreateDiscussionInput = IDL.Record({
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const CreateEventInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const CreateEventCommentInput = IDL.Record({
    'content' : IDL.Text,
    'postId' : IDL.Text,
  });
  const CreateGroupCommentInput = IDL.Record({
    'content' : IDL.Text,
    'postId' : IDL.Text,
  });
  const CreateGroupPostInput = IDL.Record({
    'content' : IDL.Text,
    'groupId' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const CreatePostInput = IDL.Record({
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const CreateResourceInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const CollectionPost = IDL.Record({
    'id' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const DiscussionPost = IDL.Record({
    'id' : IDL.Text,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
    'image' : IDL.Opt(ExternalBlob),
  });
  const EventPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'image' : IDL.Opt(ExternalBlob),
  });
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'follow' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notificationType' : NotificationType,
    'recipient' : IDL.Principal,
    'referenceId' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const EmojiReactions = IDL.Record({ 'count' : IDL.Nat, 'emoji' : IDL.Text });
  const PostReactions = IDL.Vec(EmojiReactions);
  const PlushiePost = IDL.Record({
    'id' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
    'caption' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Resource = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'username' : IDL.Text });
  const CollectionComment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
    'postId' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
    'postId' : IDL.Text,
  });
  const DiscussionComment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
    'postId' : IDL.Text,
  });
  const EventComment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
    'postId' : IDL.Text,
  });
  const GroupComment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Timestamp,
    'postId' : IDL.Text,
  });
  const GroupPost = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'groupId' : IDL.Text,
    'timestamp' : Timestamp,
    'image' : IDL.Opt(ExternalBlob),
  });
  const EmojiId = IDL.Text;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCollectionComment' : IDL.Func(
        [CreateCollectionCommentInput],
        [IDL.Text],
        [],
      ),
    'createCollectionPost' : IDL.Func([CreateCollectionInput], [IDL.Text], []),
    'createComment' : IDL.Func([CreateCommentInput], [IDL.Text], []),
    'createDiscussionComment' : IDL.Func(
        [CreateDiscussionCommentInput],
        [IDL.Text],
        [],
      ),
    'createDiscussionPost' : IDL.Func([CreateDiscussionInput], [IDL.Text], []),
    'createEvent' : IDL.Func([CreateEventInput], [IDL.Text], []),
    'createEventComment' : IDL.Func([CreateEventCommentInput], [IDL.Text], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createGroupComment' : IDL.Func([CreateGroupCommentInput], [IDL.Text], []),
    'createGroupPost' : IDL.Func([CreateGroupPostInput], [IDL.Text], []),
    'createPost' : IDL.Func([CreatePostInput], [IDL.Text], []),
    'createResource' : IDL.Func([CreateResourceInput], [IDL.Text], []),
    'deleteGroup' : IDL.Func([IDL.Text], [], []),
    'getAllCollectionPosts' : IDL.Func(
        [],
        [IDL.Vec(CollectionPost)],
        ['query'],
      ),
    'getAllCommunityGroups' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Text,
              IDL.Text,
              IDL.Principal,
              Timestamp,
              IDL.Vec(IDL.Principal),
            )
          ),
        ],
        ['query'],
      ),
    'getAllDiscussionPosts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DiscussionPost)],
        ['query'],
      ),
    'getAllEvents' : IDL.Func([], [IDL.Vec(EventPost)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllPostReactions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PostReactions))],
        ['query'],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(PlushiePost)], ['query']),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectionComments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CollectionComment)],
        ['query'],
      ),
    'getCollectionLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getDiscussionComments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DiscussionComment)],
        ['query'],
      ),
    'getDiscussionLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getEventComments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EventComment)],
        ['query'],
      ),
    'getGroupComments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GroupComment)],
        ['query'],
      ),
    'getGroupFeed' : IDL.Func([IDL.Text], [IDL.Vec(GroupPost)], ['query']),
    'getGroupMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getLikeCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getPostsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PlushiePost)],
        ['query'],
      ),
    'getReactions' : IDL.Func([IDL.Text], [PostReactions], ['query']),
    'getResource' : IDL.Func([IDL.Text], [IDL.Opt(Resource)], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserLiked' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'hasUserLikedCollection' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'hasUserLikedDiscussion' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserGroupMember' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text], [], []),
    'leaveGroup' : IDL.Func([IDL.Text], [], []),
    'listGroupPosts' : IDL.Func([IDL.Text], [IDL.Vec(GroupPost)], ['query']),
    'markAllNotificationsAsRead' : IDL.Func([], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Text], [], []),
    'removeUserFromGroup' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEvents' : IDL.Func([IDL.Text], [IDL.Vec(EventPost)], ['query']),
    'searchGroups' : IDL.Func(
        [IDL.Text],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Text,
              IDL.Text,
              IDL.Principal,
              Timestamp,
              IDL.Vec(IDL.Principal),
            )
          ),
        ],
        ['query'],
      ),
    'searchPosts' : IDL.Func([IDL.Text], [IDL.Vec(PlushiePost)], ['query']),
    'toggleCollectionLike' : IDL.Func([IDL.Text], [], []),
    'toggleDiscussionLike' : IDL.Func([IDL.Text], [], []),
    'toggleEmojiReaction' : IDL.Func([IDL.Text, EmojiId], [PostReactions], []),
    'toggleLike' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };