/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface DiscussionComment {
    id: string;
    content: string;
    author: Principal;
    timestamp: Timestamp;
    postId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CreateCommentInput {
    content: string;
    postId: string;
}
export interface CreateResourceInput {
    title: string;
    content: string;
}
export interface CreatePostInput {
    caption: string;
    image: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DiscussionPost {
    id: string;
    topic: string;
    content: string;
    author: Principal;
    timestamp: Timestamp;
    image?: ExternalBlob;
}
export interface PlushiePost {
    id: string;
    author: Principal;
    timestamp: Timestamp;
    caption: string;
    image: ExternalBlob;
}
export interface EmojiReactions {
    count: bigint;
    emoji: string;
}
export interface CreateGroupPostInput {
    content: string;
    groupId: string;
    image?: ExternalBlob;
}
export interface CreateEventCommentInput {
    content: string;
    postId: string;
}
export type PostReactions = Array<EmojiReactions>;
export interface EventPost {
    id: string;
    title: string;
    createdBy: Principal;
    description: string;
    timestamp: Timestamp;
    image?: ExternalBlob;
}
export interface CreateDiscussionCommentInput {
    content: string;
    postId: string;
}
export interface CollectionPost {
    id: string;
    author: Principal;
    timestamp: Timestamp;
    caption: string;
    image: ExternalBlob;
}
export interface EventComment {
    id: string;
    content: string;
    author: Principal;
    timestamp: Timestamp;
    postId: string;
}
export interface CreateCollectionInput {
    caption: string;
    image: ExternalBlob;
}
export interface Comment {
    id: string;
    content: string;
    author: Principal;
    timestamp: Timestamp;
    postId: string;
}
export interface GroupComment {
    id: string;
    content: string;
    author: Principal;
    timestamp: Timestamp;
    postId: string;
}
export type EmojiId = string;
export interface CreateEventInput {
    title: string;
    description: string;
    image?: ExternalBlob;
}
export interface CreateGroupCommentInput {
    content: string;
    postId: string;
}
export interface CreateCollectionCommentInput {
    content: string;
    postId: string;
}
export interface Notification {
    id: string;
    notificationType: NotificationType;
    recipient: Principal;
    referenceId: string;
    isRead: boolean;
    message: string;
    timestamp: Timestamp;
}
export interface GroupPost {
    id: string;
    content: string;
    author: Principal;
    groupId: string;
    timestamp: Timestamp;
    image?: ExternalBlob;
}
export interface Resource {
    id: string;
    title: string;
    content: string;
    createdAt: Timestamp;
    createdBy: Principal;
}
export interface CreateDiscussionInput {
    topic: string;
    content: string;
    image?: ExternalBlob;
}
export interface CollectionComment {
    id: string;
    content: string;
    author: Principal;
    timestamp: Timestamp;
    postId: string;
}
export interface UserProfile {
    bio: string;
    username: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum NotificationType {
    like = "like",
    comment = "comment",
    follow = "follow"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCollectionComment(input: CreateCollectionCommentInput): Promise<string>;
    createCollectionPost(input: CreateCollectionInput): Promise<string>;
    createComment(input: CreateCommentInput): Promise<string>;
    createDiscussionComment(input: CreateDiscussionCommentInput): Promise<string>;
    createDiscussionPost(input: CreateDiscussionInput): Promise<string>;
    createEvent(input: CreateEventInput): Promise<string>;
    createEventComment(input: CreateEventCommentInput): Promise<string>;
    createGroup(groupName: string, groupDescription: string): Promise<string>;
    createGroupComment(input: CreateGroupCommentInput): Promise<string>;
    createGroupPost(input: CreateGroupPostInput): Promise<string>;
    createPost(input: CreatePostInput): Promise<string>;
    createResource(input: CreateResourceInput): Promise<string>;
    deleteGroup(groupId: string): Promise<void>;
    getAllCollectionPosts(): Promise<Array<CollectionPost>>;
    getAllCommunityGroups(): Promise<Array<[string, string, string, Principal, Timestamp, Array<Principal>]>>;
    getAllDiscussionPosts(topic: string): Promise<Array<DiscussionPost>>;
    getAllEvents(): Promise<Array<EventPost>>;
    getAllNotifications(): Promise<Array<Notification>>;
    getAllPostReactions(): Promise<Array<[string, PostReactions]>>;
    getAllPosts(): Promise<Array<PlushiePost>>;
    getAllResources(): Promise<Array<Resource>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCollectionComments(postId: string): Promise<Array<CollectionComment>>;
    getCollectionLikeCount(postId: string): Promise<bigint>;
    getCommentsForPost(postId: string): Promise<Array<Comment>>;
    getDiscussionComments(postId: string): Promise<Array<DiscussionComment>>;
    getDiscussionLikeCount(postId: string): Promise<bigint>;
    getEventComments(postId: string): Promise<Array<EventComment>>;
    getGroupComments(postId: string): Promise<Array<GroupComment>>;
    getGroupFeed(groupId: string): Promise<Array<GroupPost>>;
    getGroupMembers(groupId: string): Promise<Array<Principal>>;
    getLikeCount(postId: string): Promise<bigint>;
    getPostsByUser(user: Principal): Promise<Array<PlushiePost>>;
    getReactions(postId: string): Promise<PostReactions>;
    getResource(resourceId: string): Promise<Resource | null>;
    getUnreadNotificationCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasUserLiked(postId: string): Promise<boolean>;
    hasUserLikedCollection(postId: string): Promise<boolean>;
    hasUserLikedDiscussion(postId: string): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isUserGroupMember(groupId: string): Promise<boolean>;
    joinGroup(groupId: string): Promise<void>;
    leaveGroup(groupId: string): Promise<void>;
    listGroupPosts(groupId: string): Promise<Array<GroupPost>>;
    markAllNotificationsAsRead(): Promise<void>;
    markNotificationAsRead(notificationId: string): Promise<void>;
    removeUserFromGroup(groupId: string, user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchEvents(searchTerm: string): Promise<Array<EventPost>>;
    searchGroups(searchTerm: string): Promise<Array<[string, string, string, Principal, Timestamp, Array<Principal>]>>;
    searchPosts(searchTerm: string): Promise<Array<PlushiePost>>;
    toggleCollectionLike(postId: string): Promise<void>;
    toggleDiscussionLike(postId: string): Promise<void>;
    toggleEmojiReaction(postId: string, emojiId: EmojiId): Promise<PostReactions>;
    toggleLike(postId: string): Promise<void>;
}
import type { CollectionPost as _CollectionPost, CreateCollectionInput as _CreateCollectionInput, CreateDiscussionInput as _CreateDiscussionInput, CreateEventInput as _CreateEventInput, CreateGroupPostInput as _CreateGroupPostInput, CreatePostInput as _CreatePostInput, DiscussionPost as _DiscussionPost, EventPost as _EventPost, ExternalBlob as _ExternalBlob, GroupPost as _GroupPost, Notification as _Notification, NotificationType as _NotificationType, PlushiePost as _PlushiePost, Resource as _Resource, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCollectionComment(arg0: CreateCollectionCommentInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollectionComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollectionComment(arg0);
            return result;
        }
    }
    async createCollectionPost(arg0: CreateCollectionInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCollectionPost(await to_candid_CreateCollectionInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCollectionPost(await to_candid_CreateCollectionInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createComment(arg0: CreateCommentInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0);
            return result;
        }
    }
    async createDiscussionComment(arg0: CreateDiscussionCommentInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiscussionComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiscussionComment(arg0);
            return result;
        }
    }
    async createDiscussionPost(arg0: CreateDiscussionInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDiscussionPost(await to_candid_CreateDiscussionInput_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDiscussionPost(await to_candid_CreateDiscussionInput_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEvent(arg0: CreateEventInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(await to_candid_CreateEventInput_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(await to_candid_CreateEventInput_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEventComment(arg0: CreateEventCommentInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createEventComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEventComment(arg0);
            return result;
        }
    }
    async createGroup(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroup(arg0, arg1);
            return result;
        }
    }
    async createGroupComment(arg0: CreateGroupCommentInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroupComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroupComment(arg0);
            return result;
        }
    }
    async createGroupPost(arg0: CreateGroupPostInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroupPost(await to_candid_CreateGroupPostInput_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroupPost(await to_candid_CreateGroupPostInput_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPost(arg0: CreatePostInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(await to_candid_CreatePostInput_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(await to_candid_CreatePostInput_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createResource(arg0: CreateResourceInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createResource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResource(arg0);
            return result;
        }
    }
    async deleteGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGroup(arg0);
            return result;
        }
    }
    async getAllCollectionPosts(): Promise<Array<CollectionPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCollectionPosts();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCollectionPosts();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCommunityGroups(): Promise<Array<[string, string, string, Principal, Timestamp, Array<Principal>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommunityGroups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommunityGroups();
            return result;
        }
    }
    async getAllDiscussionPosts(arg0: string): Promise<Array<DiscussionPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiscussionPosts(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiscussionPosts(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvents(): Promise<Array<EventPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPostReactions(): Promise<Array<[string, PostReactions]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPostReactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPostReactions();
            return result;
        }
    }
    async getAllPosts(): Promise<Array<PlushiePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionComments(arg0: string): Promise<Array<CollectionComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionComments(arg0);
            return result;
        }
    }
    async getCollectionLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionLikeCount(arg0);
            return result;
        }
    }
    async getCommentsForPost(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsForPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsForPost(arg0);
            return result;
        }
    }
    async getDiscussionComments(arg0: string): Promise<Array<DiscussionComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscussionComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscussionComments(arg0);
            return result;
        }
    }
    async getDiscussionLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscussionLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscussionLikeCount(arg0);
            return result;
        }
    }
    async getEventComments(arg0: string): Promise<Array<EventComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventComments(arg0);
            return result;
        }
    }
    async getGroupComments(arg0: string): Promise<Array<GroupComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupComments(arg0);
            return result;
        }
    }
    async getGroupFeed(arg0: string): Promise<Array<GroupPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupFeed(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupFeed(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGroupMembers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGroupMembers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGroupMembers(arg0);
            return result;
        }
    }
    async getLikeCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLikeCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLikeCount(arg0);
            return result;
        }
    }
    async getPostsByUser(arg0: Principal): Promise<Array<PlushiePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByUser(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByUser(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactions(arg0: string): Promise<PostReactions> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0);
            return result;
        }
    }
    async getResource(arg0: string): Promise<Resource | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResource(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResource(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasUserLiked(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLiked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLiked(arg0);
            return result;
        }
    }
    async hasUserLikedCollection(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedCollection(arg0);
            return result;
        }
    }
    async hasUserLikedDiscussion(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedDiscussion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedDiscussion(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUserGroupMember(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserGroupMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserGroupMember(arg0);
            return result;
        }
    }
    async joinGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinGroup(arg0);
            return result;
        }
    }
    async leaveGroup(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveGroup(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveGroup(arg0);
            return result;
        }
    }
    async listGroupPosts(arg0: string): Promise<Array<GroupPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGroupPosts(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGroupPosts(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsAsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsAsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsAsRead();
            return result;
        }
    }
    async markNotificationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async removeUserFromGroup(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUserFromGroup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUserFromGroup(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchEvents(arg0: string): Promise<Array<EventPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEvents(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEvents(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchGroups(arg0: string): Promise<Array<[string, string, string, Principal, Timestamp, Array<Principal>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGroups(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGroups(arg0);
            return result;
        }
    }
    async searchPosts(arg0: string): Promise<Array<PlushiePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPosts(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPosts(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleCollectionLike(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCollectionLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCollectionLike(arg0);
            return result;
        }
    }
    async toggleDiscussionLike(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDiscussionLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDiscussionLike(arg0);
            return result;
        }
    }
    async toggleEmojiReaction(arg0: string, arg1: EmojiId): Promise<PostReactions> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleEmojiReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleEmojiReaction(arg0, arg1);
            return result;
        }
    }
    async toggleLike(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLike(arg0);
            return result;
        }
    }
}
async function from_candid_CollectionPost_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionPost): Promise<CollectionPost> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_DiscussionPost_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscussionPost): Promise<DiscussionPost> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_EventPost_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventPost): Promise<EventPost> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GroupPost_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GroupPost): Promise<GroupPost> {
    return await from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_PlushiePost_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlushiePost): Promise<PlushiePost> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Resource]): Resource | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    author: Principal;
    timestamp: _Timestamp;
    caption: string;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    author: Principal;
    timestamp: Timestamp;
    caption: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        author: value.author,
        timestamp: value.timestamp,
        caption: value.caption,
        image: await from_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    topic: string;
    content: string;
    author: Principal;
    timestamp: _Timestamp;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    topic: string;
    content: string;
    author: Principal;
    timestamp: Timestamp;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        topic: value.topic,
        content: value.content,
        author: value.author,
        timestamp: value.timestamp,
        image: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.image))
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdBy: Principal;
    description: string;
    timestamp: _Timestamp;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    title: string;
    createdBy: Principal;
    description: string;
    timestamp: Timestamp;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        createdBy: value.createdBy,
        description: value.description,
        timestamp: value.timestamp,
        image: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    notificationType: _NotificationType;
    recipient: Principal;
    referenceId: string;
    isRead: boolean;
    message: string;
    timestamp: _Timestamp;
}): {
    id: string;
    notificationType: NotificationType;
    recipient: Principal;
    referenceId: string;
    isRead: boolean;
    message: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        notificationType: from_candid_NotificationType_n34(_uploadFile, _downloadFile, value.notificationType),
        recipient: value.recipient,
        referenceId: value.referenceId,
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    author: Principal;
    groupId: string;
    timestamp: _Timestamp;
    image: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    content: string;
    author: Principal;
    groupId: string;
    timestamp: Timestamp;
    image?: ExternalBlob;
}> {
    return {
        id: value.id,
        content: value.content,
        author: value.author,
        groupId: value.groupId,
        timestamp: value.timestamp,
        image: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: null;
} | {
    comment: null;
} | {
    follow: null;
}): NotificationType {
    return "like" in value ? NotificationType.like : "comment" in value ? NotificationType.comment : "follow" in value ? NotificationType.follow : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CollectionPost>): Promise<Array<CollectionPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CollectionPost_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiscussionPost>): Promise<Array<DiscussionPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DiscussionPost_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EventPost>): Promise<Array<EventPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EventPost_n29(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n32(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlushiePost>): Promise<Array<PlushiePost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PlushiePost_n37(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GroupPost>): Promise<Array<GroupPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GroupPost_n42(_uploadFile, _downloadFile, x)));
}
async function to_candid_CreateCollectionInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateCollectionInput): Promise<_CreateCollectionInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateDiscussionInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDiscussionInput): Promise<_CreateDiscussionInput> {
    return await to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateEventInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateEventInput): Promise<_CreateEventInput> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateGroupPostInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateGroupPostInput): Promise<_CreateGroupPostInput> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_CreatePostInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePostInput): Promise<_CreatePostInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    caption: string;
    image: ExternalBlob;
}): Promise<{
    caption: string;
    image: _ExternalBlob;
}> {
    return {
        caption: value.caption,
        image: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image)
    };
}
async function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: string;
    content: string;
    image?: ExternalBlob;
}): Promise<{
    topic: string;
    content: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        topic: value.topic,
        content: value.content,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    image?: ExternalBlob;
}): Promise<{
    title: string;
    description: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        title: value.title,
        description: value.description,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    groupId: string;
    image?: ExternalBlob;
}): Promise<{
    content: string;
    groupId: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        content: value.content,
        groupId: value.groupId,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
